### ISSUE TITLE
Missing Settings Icon and 'Messenger' Text

### ISSUE THREAD

**Issue by rpartha** [sindresorhus/caprine#1002]
![image](https://user-images.githubusercontent.com/3248921/61344697-31d56800-a820-11e9-80bc-a51e0530579a.png)

![image](https://user-images.githubusercontent.com/3248921/61344730-59c4cb80-a820-11e9-94c5-31a246a7b291.png)

The settings icon and Messenger text present on messenger.com do not show here. The first picture is your app (modified using custom css) and the second one is Messenger website. Even without custom css (aka source), the icon still isn't present. I see similar issue has been merged into master but the issue obviously still persists. I do not have the new Messenger UI yet.

Here's the custom css:

```css
/*
This is the custom styles file where you can add anything you want.
The styles here will be injected into Caprine and will override default styles.
If you want to disable styles but keep the config, just comment the lines that you don't want to be used.

Here are some dark mode color variables to get you started.
Edit them to change color scheme of Caprine.
Press Command/Ctrl+R in Caprine to see your changes.
*/

/* original is commented  */
/*:root {
	--base: #000;
	--base-ninety: rgba(255, 255, 255, 0.9);
	--base-seventy-five: rgba(255, 255, 255, 0.75);
	--base-seventy: rgba(255, 255, 255, 0.7);
	--base-fifty: rgba(255, 255, 255, 0.5);
	--base-fourty: rgba(255, 255, 255, 0.4);
	--base-thirty: rgba(255, 255, 255, 0.3);
	--base-twenty: rgba(255, 255, 255, 0.2);
	--base-five: rgba(255, 255, 255, 0.05);
	--base-ten: rgba(255, 255, 255, 0.1);
	--base-nine: rgba(255, 255, 255, 0.09);
	--container-color: #000000;
	--container-dark-color: #000000;
	--list-header-color: #000000;
	--blue: #0084ff;
	--selected-conversation-background: linear-gradient(hsla(209, 110%, 45%, 0.9), hsla(209, 110%, 42%, 0.9));
}*/

:root {
    --base: #000;
    --base-ninety: rgba(255, 255, 255, 0.9);
    --base-seventy-five: rgba(255, 255, 255, 0.75);
    --base-seventy: rgba(255, 255, 255, 0.7);
    --base-fifty: rgba(255, 255, 255, 0.5);
    --base-fourty: rgba(255, 255, 255, 0.4);
    --base-thirty: rgba(255, 255, 255, 0.3);
    --base-twenty: rgba(255, 255, 255, 0.2);
    --base-five: rgba(255, 255, 255, 0.05);
    --base-ten: rgba(255, 255, 255, 0.1);
    --base-nine: rgba(255, 255, 255, 0.09);
    --container-color: #000000;
    --container-dark-color: #000000;
    --list-header-color: #000000;
    --blue: #0084ff;
    --selected-conversation-background: rgba(0, 0, 0, .05);
}

body{background: #ffffff !important}
h1{color:#ffffff}
h2{font-size: 18px !important; font-weight: bold !important; }                      
li a:hover{cursor:pointer !important} 
._1ht1._1ht2{background:rgba(0, 0, 0, .05) !important; color:#ffffff !important}
._17w2 *{color: #ffffff !important}
._1ht1._1ht2 *{ color:#ffffff !important}
._1t2u{border-left: 0px !important;}
._fl2{ padding: 8px 8px !important}
._5iwm input._58al{background:#ffffff !important; box-shadow: 0px 0px 5px rgba(0,0,0,0.05) !important}
._673w{text-align:left !important;}
._5743{ padding-left: 6px !important;}
```
