### ISSUE TITLE
Hide Conversation Scrollbar

### ISSUE THREAD

**Issue by wahyupriadi** [sindresorhus/caprine#1540]
![Screenshot from 2021-01-30 12-37-36](https://user-images.githubusercontent.com/28992650/106348392-881dd500-62f8-11eb-9951-b2f162ff11e9.png)

How to hide this conversation scrollbar?
I know some css in order to hide this scrollbar, but what class?

**Comment by dusansimic** [comment]
Try this one:
```css
.buofh1pr.j83agx80.eg9m0zos.ni8dbmo4.cbu4d94t.gok29vw1 {
	overflow-y: hidden;
}
```
