### ISSUE TITLE
White scroll bars with dark theme

### ISSUE THREAD

**Issue by vanushwashere** [sindresorhus/caprine#1549]
Very annoying white scrollbars on dark mode.

OS: Kubuntu 20.04
Caprine:  2.52.0 2021-01-25
![image](https://user-images.githubusercontent.com/24995381/107013500-df69ec80-67b3-11eb-8d59-7398b274c3f4.png)

**Comment by dusansimic** [comment]
Hi! The far right will be removed in the next release. The left one can't be removed without hiding the scroll bar so we won't remove that for now. It can however be removed with Custom Styles. Try these ones.

```css
body::-webkit-scrollbar {
	width: 0;
}
.buofh1pr.j83agx80.eg9m0zos.ni8dbmo4.cbu4d94t.gok29vw1::-webkit-scrollbar {
	width: 0;
}
```

**Comment by vanushwashere** [comment]
Oh, thanks! It fixed the far right one and hid the one in the conversation.

**Comment by HugLifeTiZ** [comment]
Hiya. I'm thinking about migrating from Ferdi to standalone apps for all my services, including this one. Ferdi had the same problem, and I like this bit of CSS to fix it. It results in a really nice compact scrollbar for the places where it makes sense to keep them.

```css
::-webkit-scrollbar-track, ::-webkit-scrollbar, ::-webkit-scrollbar-corner {
	background-color: none;
}
::-webkit-scrollbar {
	width: 10px;
	overflow-x: hidden;
}
body::-webkit-scrollbar {
	width: 0;
}
::-webkit-scrollbar-thumb {
	border-radius: 10px;
	background-color: #8b8b8b60;
	background-clip: content-box;
	border: 2px solid transparent;
}
::-webkit-scrollbar-thumb:hover {	
	background-color: #8b8b8b90;
}
```
