### ISSUE TITLE
Emoji wrongly displayed in name on the sidebar

### ISSUE THREAD

**Issue by maxoku** [sindresorhus/caprine#1578]
I have a group which has an emoji (rofl) in its name. Few months ago when I started to use Caprine it had problems to display it on the sidebar. It could display it or a rectangle. Refreshing or switching views was fixing it to display the emoji.

After new UI it always displayed it properly. After today's update it stopped. I've tried switching views like before, but it didn't help. I've refreshed it with Ctrl+R and I saw the emoji to be immediately replaced by rectangle again.

This emoji is displayed properly everywhere else but not on the sidebar if it's in the name. It displays properly this emoji if it's in a message preview though. It also displays properly in the name when it's anywhere else besides sidebar.

Could you fix that the emoji wouldn't be replaced by a rectangle?

---

Caprine 2.52.1
Electron 10.1.5
win32 6.3.9600
Locale: pl

**Comment by maxoku** [comment]
![em1](https://user-images.githubusercontent.com/17256400/110636313-6b54a700-81ac-11eb-865d-cd4737ef1441.jpg)
After refreshing, emoji is displayed.
![em2](https://user-images.githubusercontent.com/17256400/110636395-7c9db380-81ac-11eb-9a87-34c91a950a3e.jpg)
After a moment, the emoji was replaced by a rectangle.
Emoji 🤣 called "rolling on the floor laughing" (rofl).

**Comment by dusansimic** [comment]
I'm not able to reproduce this issue on my machine. Could you try adding the following css to the custom style?
```css
body {
	font-family:
		-apple-system,
		BlinkMacSystemFont,
		'Segoe UI',
		Roboto,
		Oxygen-Sans,
		Ubuntu,
		Cantarell,
		'Helvetica Neue',
		sans-serif,
		'Apple Color Emoji',
		'Segoe UI Emoji',
		'Segoe UI Symbol' !important;
	text-rendering: optimizeLegibility !important;
	font-feature-settings: 'liga', 'clig', 'kern';
}
```

You can add a custom style by going to the menu File -> Caprine settings -> Advanced -> Custom styles. Paste the css snippet at the end of file, save it and close the file. Then restart Caprine.
