### ISSUE TITLE
Empty space at top after update

### ISSUE THREAD

**Issue by maxoku** [sindresorhus/caprine#1604]
After today's update there is an empty space at top. Please fix it or maybe write a css code fixing it temporarily before the next release.
![caprine margin](https://user-images.githubusercontent.com/17256400/114164649-d3bdb200-992b-11eb-8f1a-6312ca9502fc.jpg)

**Comment by Gregman-js** [comment]
Same. Dark mode - related

**Comment by dusansimic** [comment]
Just a note, this is unrelated to the update, it is present on both v2.52.2 and v2.52.3. It will be fixed over the weekend however I don't know when the fix will be released.

**Comment by maxoku** [comment]
@dusansimic 
That's weird, cuz I didn't have that before the update. It literally appeared after I've updated it today.
And as I said maybe a css could temporary fix it before the update?

**Comment by dusansimic** [comment]
@maxoku

> That's weird, cuz I didn't have that before the update. It literally appeared after I've updated it today.

I'm using v2.52.2 right now and I have this issue.

> And as I said maybe a css could temporary fix it before the update?

It could, however I will only be able to do it over the weekend. I'll make a pr and anyone could just copy the required css to add it as custom css until the update is released.

**Comment by nforro** [comment]
Quick & dirty workaround. Add this to your `custom.css`:

```css
html.dark-mode .be9z9djy {
    top: 0;
}

html.dark-mode .jgljxmt5 {
    min-height: 100vh;
}

html.dark-mode .gitj76qy {
    max-height: 100vh;
}
```
