### ISSUE TITLE
How to change chat bubble color?

### ISSUE THREAD

**Issue by dnlw07** [sindresorhus/caprine#1855]
Hello,
could anyone please guide me how to change default blue color of the chat bubble into gradient similar to new messenger?

I was going through available issues, but I wasn't able to find solution.
Tried to randomly modify `custom.css` but without result.

**Comment by mquevill** [comment]
I would suggest using the official theming options within Messenger, since the classes of messages are not always the most consistent/stable.

You'll be limited to the colors that Facebook provides. In the upper right, click on the 3 dots to open the right menu. Under "Customize chat", you can change the theme colors from there.

![Facebook Messenger Themes](https://user-images.githubusercontent.com/17033543/180102448-a06e766e-93ec-444e-8ddc-8877b11118fb.png)


--------

*[ This will not necessarily work well, but might help you to get started. ]*

If you are wanting to apply totally custom themes, try putting the below code into `custom.css`. Change the `rgb(0,0,0)` to whatever RGB color you want. You need the `!important` tag to override any other styles. (This will not change other theming elements like the "Change theme" option would.)
```css
.cxgpxx05.d1544ag0.sj5x9vvc.tw6a2znq.l9j0dhe7.ni8dbmo4.stjgntxs.e72ty7fz.qlfml3jp.inkptoze.qmr60zad.jm1wdb64.qv66sw1b.ljqsnud1.odn2s2vf.tkr6xdv7 {
    background-color: rgb(0,0,0) !important;
}
```
