### ISSUE TITLE
White message bubbles in dark mode

### ISSUE THREAD

**Issue by theonlytechnohead** [sindresorhus/caprine#2148]
![image](https://github.com/sindresorhus/caprine/assets/28742353/ce79e026-b702-45ef-9791-143a8b8500b6)

`--chat-incoming-message-bubble-background-color` is set to `#F0F0F0` by Messenger, even in dark mode.

Adding the following lines to `custom.css` fixes the issue:

```css
div.x1xr0vuk {
	--chat-incoming-message-bubble-background-color: #555555;
}
```

---

Caprine 2.59.3
Electron 25.9.8
win32 10.0.19045
Locale: en-GB

**Comment by ienzo** [comment]
Had this issue as well on Linux. Can confirm the above fix works for me too.

**Comment by DerpDerpingtonIsHere** [comment]
Oddly having this issue in Windows and not Linux.

**Comment by ienzo** [comment]
> Oddly having this issue in Windows and not Linux.

Probably because this is an issue with Facebook tweaking the CSS. There's nothing inherent about Linux that makes it more buggy than Windows or vice versa.

**Comment by mquevill** [comment]
Yes, this is coming from CSS changes on Facebook's end. Changing the `--chat-incoming-message-bubble-background-color` will work for now, but it may require a bit more investigation into what exactly needs to be changed in the CSS. (Until the back-end CSS is changed again...)

I would recommend the following _temporary_ addition to `custom.css` edited through File > Caprine Settings > Advanced > Custom Styles. The addition of `html.dark-mode` will ensure that the style is only applied when dark mode is used.

```css
html.dark-mode .x1xr0vuk {
	--chat-incoming-message-bubble-background-color: #555555;
}
```
