### ISSUE TITLE
Support for the change of custom Font for Khmer Font or Khmer Unicode

### ISSUE THREAD

**Issue by kjlawrencelaw** [sindresorhus/caprine#429]
My mon is Cambodia-Chinese and usually she will send me some texts in Khmer,
(when she dunno how to express herself in Chinese or English),
But,
here is some example since I installed tons of khmer font for Mac,
![image](https://user-images.githubusercontent.com/13857562/38774587-1177805a-409f-11e8-9b0b-ab9e28204b6a.png)
and,
this is the result I see,
![image](https://user-images.githubusercontent.com/13857562/38774573-d2d71cfc-409e-11e8-87f8-15ac59a10b2b.png)
...
quite awful,
although I can't read it and literally just copy it and paste to "Google Translate",
so,
```
I would like to ask that,
is there any way,
to change the custom font like, khmer or sth other else.
```

Postscript,
im quite new to the GIthub and "coding" stuff,
if yes there it is,
please,
treat me like a newbie and don't be hesitate to tell me in more and more simplicity please.

**Comment by dusansimic** [comment]
You could add custom CSS (the thing that specifies how the page is going to look, including fonts) that Caprine will load. To edit custom CSS go to `File -> Caprine Settings -> Advanced -> Custom Styles`. An editor should open. In that editor, just paste this at the end of the file:

```css
html {
  font-family: "Your Khmer Font", -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen-Sans, Ubuntu, Cantarell, "Helvetica Neue", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol" !important;
}
```

Replace `Your Khmer Font` with the font name you want to use.

I hope this helps.
