### ISSUE TITLE
Customize "Message list: your message bubble"

### ISSUE THREAD

**Issue by jeremyong** [sindresorhus/caprine#886]
The style override for `.o46:not(._nd_) ._hh7` is overridden in messenger when the user has a defined "custom color" within Messenger itself.

Is there any way to inject the `custom.css` files in a way that bypasses these options? The main rationale is that the enduser may want the Facebook provided stylings when using messenger in a browser, but different settings when using Caprine.

Thanks!

**Comment by sadmanf** [comment]
What `custom.css` file are you referencing? Are you just trying to create custom styles in Caprine? If you set styles in Messenger and then adjust your Caprine settings locally, do they still override?

**Comment by jeremyong** [comment]
Yes the caprine local `custom.css` file does not take into effect if you've changed the chat bubble color in facebook's interface at any time.

**Comment by dusansimic** [comment]
You should be able to change the colour of message bubbles with class `.x1tlxs6b.x1g8br2z.x1gn5b1j.x230xth.x14ctfv.x1okitfd.x6ikm8r.x10wlt62.x1mzt3pk.x1y1aw1k.xn6708d.xwib8y2.x1ye3gou.x1n2onr6.x13faqbe.x1vjfegm`.

You will however need to apply the properties with the `!important` rule like this:

```css
.x1tlxs6b.x1g8br2z.x1gn5b1j.x230xth.x14ctfv.x1okitfd.x6ikm8r.x10wlt62.x1mzt3pk.x1y1aw1k.xn6708d.xwib8y2.x1ye3gou.x1n2onr6.x13faqbe.x1vjfegm {
  background-color: red !important;
}
```

This will result in the style being forcefully applied and Facebooks styles can't override it. I can see tho that you'll need to differentiate between a couple of types of message bubbles since they have different classes that identify them.
